### ISSUE TITLE
[Suggestion] Mob white/blacklist

### ISSUE THREAD

**Issue by SeriousCreeper** [yorkeJohn/Burlap-Sack#1]
Heya,

really liking this mod, having a low-tech way of capturing animals is great. I'm using it in combination with terrafirmacraft that adds larger animals such as black bears, that i would rather not be able to pick up with the bags. 

Would it be possible to get a whitelist or blacklist of which animals are allowed to be captured? 

Cheers,
SC

**Comment by yorkeJohn** [comment]
Sure thing!

**Comment by SeriousCreeper** [comment]
Thanks a lot! :D
