### ISSUE TITLE
How do bag a mount?

### ISSUE THREAD

**Issue by Zarepheth** [yorkeJohn/Burlap-Sack#3]
I've been riding donkey. Now I want to bag it, but I get the mount UI instead of a donkey in a sack.
Is there a way to bag my donkey?

I'm guessing I'll see the same problem with any other mount: Llama, Horse, etc...

**Comment by Zarepheth** [comment]
If I right-click the mount with the burlap sack in my hand, I end up mounted. If I [shift] right-click with the sack in my hand, I see the mount UI.

I don't know the technical details of Minecraft or Forge, but I'm guessing this mod needs a keybind to distinguish between the normal mount functions and the bagging function.

**Comment by yorkeJohn** [comment]
I am unable to reproduce the described issue in the latest (1.17.1) version of Burlap Sack. Right-click with Burlap Sack captures the mount, Shift+Right-click opens the mount UI.
